### ISSUE TITLE
给本仓库提的建议

### ISSUE THREAD

**Issue by purofle** [CosineMath/BoatApp#12]
如果这个项目仅仅是后端 请写wiki，方便开发者进行二次开发；
如果这个项目是android app,请带上build.gradle

**Comment by qaz6750** [comment]
注意要build.gradle自己编写或者Android studio生成，还有这不是一个Android studio项目，自行尝试迁移

**Comment by purofle** [comment]
> 注意要build.gradle自己编写或者Android studio生成，还有这不是一个Android studio项目，自行尝试迁移

为什么0202年还有人不用gradle（

**Comment by CosineMath** [comment]
相关说明正在编写。不过学业繁忙（摸鱼繁忙。
