### ISSUE TITLE
Boat question?

### ISSUE THREAD

**Issue by KULTO10** [CosineMath/BoatApp#14]
Why some youtubers in youtube they can't share the link? Because your gonna mad? and they said its blacklisted app and why? 

Why they hide it?
https://youtu.be/YEPql_lWxNY
https://youtu.be/7lQife9OBzk

One more question ShirosakiMio and you are only one? 

![Screenshot_20200828_023902](https://user-images.githubusercontent.com/70342097/91482034-f983d280-e8d7-11ea-93b8-7b3a72aa210f.jpg)

**Comment by Malaska678** [comment]
@Maxiedoopheyhey Are you the heyhey in discord. Github name: minecraftname dscordname

**Comment by KULTO10** [comment]
> @Maxiedoopheyhey Are you the heyhey in discord. Github name: minecraftname dscordname

Yes

**Comment by CosineMath** [comment]
They might modify the boat and are not will to share with others.

**Comment by KULTO10** [comment]
> They might modify the boat and are not will to share with others.

so i cant get the boat lava ,simple boat and boat_H20. So they just modify it? Some people have simple boat and boat lava they said its blacklist version but shirosaki said that blacklist version is another version of boat

Im in pain that because i cant understand chinese i found a link for boat lava in bilibili but i need to download pan baidu software app (i just read the url)

and how to get simple boat?

**Comment by CosineMath** [comment]
Sorry but I don't know much because there are too many modified versions.

**Comment by KULTO10** [comment]
> Sorry but I don't know much because there are too many modified versions.

Oh okay but the original is just the boat app and that was you who made it right?
