### ISSUE TITLE
似乎是华为系统上出现的特定问题，本人meizu能够正常使用zip进行本地导入，但其他两台华为出错，均报此错误

### ISSUE THREAD

**Issue by dfsjklw** [CosineMath/BoatApp#18]
程序崩溃了！ java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=233, result=-1, data=Intent { dat=content://com.huawei.hidisk.fileprovider/root/storage/emulated/0/1/sina/1.12.2极致优化版第4版.zip typ=application/zip flg=0x3 }} to activity {com.mio.boat/cosine.boat.Activity_Download}: java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: []  at android.app.ActivityThread.deliverResults(ActivityThread.java:5078)  at android.app.ActivityThread.handleSendResult(ActivityThread.java:5120)  at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)  at android.os.Handler.dispatchMessage(Handler.java:112)  at android.os.Looper.loop(Looper.java:216)  at android.app.ActivityThread.main(ActivityThread.java:7625)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) Caused by: java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: []  at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:340)  at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)  at cosine.boat.FileChooseUtil.getDataColumn(FileChooseUtil.java:138)  at cosine.boat.FileChooseUtil.getPath(FileChooseUtil.java:119)  at cosine.boat.Activity_Download.onActivityResult(Activity_Download.java:479)  at android.app.Activity.dispatchActivityResult(Activity.java:7797)  at android.app.ActivityThread.deliverResults(ActivityThread.java:5071)  ... 11 more  2020-10-08 19:57:43: Splash created 2020-10-08 19:57:44: Splash resumed 2020-10-08 19:57:45: Splash paused 2020-10-08 19:57:45: Activity_Download created 2020-10-08 19:57:45: Activity_Download resumed 2020-10-08 19:57:45: Splash destroyed 2020-10-08 19:57:48: Activity_Download paused  Build version: 1.0 Build date: 2020-06-06 19:40:44 Current date: 2020-10-08 19:57:54 Device: HUAWEI INE-AL00  Stack trace: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=233, result=-1, data=Intent { dat=content://com.huawei.hidisk.fileprovider/root/storage/emulated/0/1/sina/1.12.2极致优化版第4版.zip typ=application/zip flg=0x3 }} to activity {com.mio.boat/cosine.boat.Activity_Download}: java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: []  at android.app.ActivityThread.deliverResults(ActivityThread.java:5078)  at android.app.ActivityThread.handleSendResult(ActivityThread.java:5120)  at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)  at android.os.Handler.dispatchMessage(Handler.java:112)  at android.os.Looper.loop(Looper.java:216)  at android.app.ActivityThread.main(ActivityThread.java:7625)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) Caused by: java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: []  at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:340)  at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)  at cosine.boat.FileChooseUtil.getDataColumn(FileChooseUtil.java:138)  at cosine.boat.FileChooseUtil.getPath(FileChooseUtil.java:119)  at cosine.boat.Activity_Download.onActivityResult(Activity_Download.java:479)  at android.app.Activity.dispatchActivityResult(Activity.java:7797)  at android.app.ActivityThread.deliverResults(ActivityThread.java:5071)  ... 11 more  User actions: 2020-10-08 19:57:43: Splash created 2020-10-08 19:57:44: Splash resumed 2020-10-08 19:57:45: Splash paused 2020-10-08 19:57:45: Activity_Download created 2020-10-08 19:57:45: Activity_Download resumed 2020-10-08 19:57:45: Splash destroyed 2020-10-08 19:57:48: Activity_Download paused

**Comment by CosineMath** [comment]
？
这是修改版的boat，你应该找修改作者而不是我。
