### ISSUE TITLE
Make Compiled APK in Release

### ISSUE THREAD

**Issue by ghost** [CosineMath/BoatApp#2]
In the release tab,in the project should have some snapshots so people can test and report issues.

**Comment by CosineMath** [comment]
Thanks for your suggestion!

Please have a look on MCinaBox (https://github.com/longjunyu2/MCinaBox), which uses Boat as backend library for running Minecraft and provides a better frontend launcher for Minecraft. It has already released some APK packages. 

I am now working together with the author of MCinaBox and so the releases of MCinaBox are also the releases of BoatApp.

**Comment by Mikar9** [comment]
Boatapp very hard to use
