### ISSUE TITLE
How to set up

### ISSUE THREAD

**Issue by minerchino** [CosineMath/BoatApp#20]
Excuse me how do i set up this launcher i heard it is can run 1.16 smoothly

**Comment by Hacker1254** [comment]
https://github.com/AOF-Dev/BoatApp#building

**Comment by Hacker1254** [comment]
Also you can also download it here https://github.com/ShirosakiMio/BoatApp/releases/

**Comment by minerchino** [comment]
> Also you can also download it here https://github.com/ShirosakiMio/BoatApp/releases/

Configtxt is missing

**Comment by Hacker1254** [comment]
oh

**Comment by TSaltedfishKing** [comment]
oh

**Comment by Hacker1254** [comment]
https://github.com/AOF-Dev/BoatApp/issues/2

**Comment by CosineMath** [comment]
Boat is not to be an MC launcher but a set of packages for running Minecraft and others. Although it includes a tiny MC launcher, it is only for test and will be removed soon. Please look at some launcher apps using Boat.
