### ISSUE TITLE
如何升级sdk

### ISSUE THREAD

**Issue by Tungstend** [CosineMath/BoatApp#24]
Sdk高于22就闪退，如何升级至sdk29或30

**Comment by CosineMath** [comment]
这是因为没有包含动态申请权限的代码。在手机上手动授予权限可解决。要升级sdk请参照Android相关适配说明。

**Comment by Tungstend** [comment]
感谢

CosineMath ***@***.***> 于 2021年7月29日周四 下午5:18写道：

**Comment by Tungstend** [comment]
但是添加动态获取权限后仍不能启动游戏，所有库都加载了就是不能启动游戏

韩金龙 ***@***.***> 于 2021年7月30日周五 下午1:13写道：

**Comment by Tungstend** [comment]
添加了动态申请权限的代码，从sdk22升级至29，此外没有其他改动，log中显示所需的库都已加载，但游戏无法启动，请问除了申请权限还需要做什么改动吗

CosineMath ***@***.***> 于 2021年7月29日周四 下午5:18写道：

**Comment by CosineMath** [comment]
你不抓点log发出来看看我怎么知道呢。。。
