### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by FENG-MASTER** [CosineMath/BoatApp#25]
作者大大你好，很高兴能找到一款使用起来很舒服，页面又好看的手机端java版启动器，我没想到手机游玩大型整合包居然还这么流畅。有个小的建议希望你能采纳。
方向键控制的时候，长按某个方向后，似乎默认会一直按着，就算我放开方向键，也会一直在走，我理解这是为了手机操作上的优化，但我相信和我一样不怎么适应的人应该不在少数，能否将这个优化设置个开关，方便切换呢？

最后还是谢谢你给我们提供了这么好的启动器，感谢！

**Comment by CosineMath** [comment]
你走错地方了，Boat只是一套环境，不是启动器。（以前那个简陋的启动器早删了。。。）
你可能要找的是Boat-澪或者H2O2之类的吧。他们有自己的仓库，不在这里。
