### ISSUE TITLE
where will I get the apk ??

### ISSUE THREAD

**Issue by ShiromcID** [CosineMath/BoatApp#3]
How do I find the apk?

**Comment by CosineMath** [comment]
https://github.com/CosineMath/BoatApp/issues/2

**Comment by ShiromcID** [comment]
You suggested McinaBox but I've seen people use this apk boat release, but they keep it a secret
https://youtu.be/GwfAi52ojMA

**Comment by CosineMath** [comment]
Emmm, the launcher for Minecraft of boat is only for testing now, so the functions are poor and it is difficult to use. That is why I suggested mcinabox instead which **use the same backend libraries** but has better frontend launcher. So I think it is not needed to release packages of BoatApp. If it is really needed then I would put some releases.

(P.S. There are many modified released packages of BoatApp in Chinese bbs about Minecraft. Why they keep boat as a secret???)
