### ISSUE TITLE
为什么跳转boat闪退回主页

### ISSUE THREAD

**Issue by ghost** [CosineMath/BoatApp#5]
我尝试就**跳转boat的LauncherActivity主界面的时候**，他闪退回了主页

**Comment by CosineMath** [comment]
描述具体一点，谢谢。

**Comment by ghost** [comment]
具体点就是我尝试写一个应用，里面有一个控件跳转boat，但是我跳转的时候，闪回了主界面

**Comment by CastusMike** [comment]
Ever have links to download apps?
I love this

**Comment by ghost** [comment]
你要？我qq发给你,我qq:2838632319

**Comment by CastusMike** [comment]
I want that app, please send me the link via my gmail, Thank you very much
💗💗

Vào 11:24, T.2, 4 Th5, 2020 小叶子 <notifications@github.com> đã viết:

**Comment by ghost** [comment]
请出示你的gmail,注意这是中文界面的

**Comment by CastusMike** [comment]
Oh sorry , My gmail : Castusmike@gmail.com

Vào 11:33, T.2, 4 Th5, 2020 小叶子 <notifications@github.com> đã viết:
