### ISSUE TITLE
无法正确处理java.nio.file.Files.createTempFile

### ISSUE THREAD

**Issue by PTALTS-LK** [CosineMath/BoatApp#9]

**Comment by CosineMath** [comment]
你倒是给点说明啊。

**Comment by PTALTS-LK** [comment]
> 你倒是给点说明啊。

在我运行录像回放模组时无法保存录制文件
Mod从那边说，他们无法解决

**Comment by CosineMath** [comment]
`java.nio.file.Files.createTempFile`  这个怎么来的？既然知道这个肯定是看过log，不妨发一下？

**Comment by PTALTS-LK** [comment]
> 你倒是给点说明啊。

Report this to the boat launcher, it looks like their Java build doesn't properly support java.nio.file.Files.createTempFile and they need to fix that. Nothing we can do about it.
这是原话

**Comment by PTALTS-LK** [comment]
https://github.com/ReplayMod/ReplayMod/files/4941365/crash-2020-07-18_08.21.05-client.txt

**Comment by CosineMath** [comment]
谢谢反馈。我会去研究一下具体问题所在。（另，反馈不要扔一句话就跑，谁知道你怎么弄的）

**Comment by khanhduytran0** [comment]
Set `java.io.tmpdir` property to change /tmp path.

**Comment by CosineMath** [comment]
已解决。
